### PR TITLE
New bzr init subcommand, and rename handling

### PR DESCRIPTION
**Pull request by niemeyer**
These changes introduce a new "git bzr init" subcommand which enables starting the development
process within git, and thus enabling one to push brand new branches into Launchpad.

Without further arguments, "git bzr init" will initialize the bzr/<branch> tracking branch for the current branch (including master), otherwise, it initializes the bzr/<target> tracking branch for the named target.

In addition to that, it also adds the -M flag to git fast-export, so that renames are properly considered by bzr.

### CODE REVIEW

**Comment by termie** [comment]
looks awesome, thanks :) will merge momentarily

**Comment by niemeyer** [comment]
Thanks!

**Comment by termie** [comment]
merged, added some tests (they'd be nice if you want to include them when you contribute in the future) and had to remove the init based on a branch because it wasn't working correctly, but you get the same effect by using 'master' all the time:

https://github.com/termie/git-bzr-ng/commit/9eb799199551edf8d6ace82e0d1502fb29d84532

**Comment by niemeyer** [comment]
That's awesome, thanks, and sorry for the lack of tests.

**Pull request merged**
